CREATE TABLE IF NOT EXISTS gebruikers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  naam TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  pin_hash TEXT NOT NULL,
  rol TEXT NOT NULL,
  actief INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS drankconfig (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  gebouw TEXT NOT NULL,
  zaal TEXT NOT NULL DEFAULT 'Alle zalen',
  volgorde INTEGER NOT NULL DEFAULT 0,
  categorie TEXT NOT NULL DEFAULT 'Overig',
  dranksoort TEXT NOT NULL,
  eenheid TEXT NOT NULL DEFAULT 'flesje',
  flesjes_per_bak INTEGER NOT NULL DEFAULT 24,
  locatie TEXT NOT NULL DEFAULT 'Koelcel',
  prijs_per_stuk REAL NOT NULL DEFAULT 0,
  actief INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_drankconfig_gebouw ON drankconfig(gebouw);
CREATE INDEX IF NOT EXISTS idx_drankconfig_dranksoort ON drankconfig(dranksoort);

CREATE TABLE IF NOT EXISTS voorraad (
  gebouw TEXT NOT NULL,
  drank TEXT NOT NULL,
  stock REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (gebouw, drank)
);

CREATE TABLE IF NOT EXISTS voorraad_mutaties (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  gebouw TEXT NOT NULL,
  drank TEXT NOT NULL,
  mutatie_type TEXT NOT NULL,
  hoeveelheid REAL NOT NULL,
  datum TEXT NOT NULL,
  registratie_id TEXT,
  aangemaakt_op TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_mutaties_gebouw ON voorraad_mutaties(gebouw, drank);

CREATE TABLE IF NOT EXISTS registraties (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  registratie_id TEXT NOT NULL UNIQUE,
  gebouw TEXT NOT NULL,
  zaal TEXT,
  datum TEXT NOT NULL,
  vereniging TEXT,
  fase TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  aangemaakt_door TEXT,
  aangemaakt_op TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO gebruikers (naam,email,pin_hash,rol,actief) VALUES
('Marilyne Volckaert','marilyne.volckaert@moorslede.be','pbkdf2$100000$mow_E56lH_XBs0I5FFxLxg$Fw3DhPrgXMHL8a1Md-Yz254egyA7Xed9ey7NVd3Lt48','beheerder',1),
('Dylan Hoornaert','dylan.hoornaert@moorslede.be','pbkdf2$100000$aUYz6JIvJ8O4BQe8TfGc4A$pxZHO8ilA_UQWC7SI1UP1FGtoLthEoy_u5XWI_qkjnQ','beheerder',1),
('Niek Lyphout','niek.lyphout@moorslede.be','pbkdf2$100000$VA2HKO3yek_o2M2qx1A2Og$5x8NlDEgottqMp113GOL-l7BA5NU88uMZItDAkqSCIM','beheerder',1),
('Myriam Geldof','myriam.geldof@moorslede.be','pbkdf2$100000$Rdcp59mcn59Z7L7ZWv8OJA$zMUnSroFHb6IcnP4O19iwpmp9MOW2S2OSpZuxiJR7DM','personeel',1),
('Nathalie Verkyndere','nathalie.verkyndere@moorslede.be','pbkdf2$100000$ZwhuTFr-KoHP87NpI_Z9gQ$ildSAkojvpgBEIFddDrGbJpbXX47Z6abJsG8nfyRJJE','personeel',1),
('Eveline Devogele','eveline.devogele@moorslede.be','pbkdf2$100000$vuBrvNXbdLbTLMQ0TLILkQ$5aSCzB7GGlxyL7U9yghhCS4lujd25JGgYzMnHvFLs1E','personeel',1),
('Emmely Liebrand','emmely.liebrand@moorslede.be','pbkdf2$100000$FoE7APFpYb8-UN2VZTMyTg$oNAAN06rVQ7oW_NUkoEpOBHRDOBE2cvRlH51D0gLfGc','personeel',1),
('Tom Vanmoerkerke','tom.vanmoerkerke@moorslede.be','pbkdf2$100000$dEoC-Jliib-HWIxZEUjwmw$gaAdS4SK2odN2BT81V3pH5vTLTu5GvPHTr79fFDi-74','personeel',1),
('Lie Cauwelier','lie.cauwelier@moorslede.be','pbkdf2$100000$rmVQy6UlL0Sy660cg20qEQ$TplZa1FNUrSgfzMGBVa6j7UqMIKi12aMq1mBt5DVE1E','personeel',1),
('Olivier Depickere','olivier.depickere@moorslede.be','pbkdf2$100000$HaRk6OhUn_63r2eYf1uYLw$h-JGAnuLxyJ73cJL-mIl4v59h2YfnaIk6Fp69PYQ2GQ','personeel',1),
('Peter Schoutteten','peter.schoutteten@moorslede.be','pbkdf2$100000$cbucVVGSBI7TMvBTQxvSTA$EGwgBdIQK8jEI9cY2kG2vjF1faQZt0Ih9eyYbKOn0vo','personeel',1),
('Tom Vanoverberghe','tom.vanoverberghe@moorslede.be','pbkdf2$100000$9powJKHUkSmOb34cpK04dQ$otxOcr8lV2E0-qv1BW9918w-1Ead9kQHN7JhXuaE2nU','personeel',1),
('Joris Vanderhulst','joris.vanderhulst@moorslede.be','pbkdf2$100000$3lPD7SFs_aNSm8U0J2hJ_A$0KVFkw_BycE62rWsh0vYq0DNphJTdhNb6J-nXnDlZtM','personeel',1);

INSERT INTO drankconfig (gebouw,zaal,volgorde,categorie,dranksoort,eenheid,flesjes_per_bak,locatie,prijs_per_stuk,actief) VALUES
('GC De Bunder','Alle zalen',1,'Non-alcoholisch','Chaudfontaine plat 20 cl','flesje',24,'Koelcel',0.54,1),
('GC De Bunder','Alle zalen',2,'Non-alcoholisch','Chaudfontaine bruis 20 cl','flesje',24,'Koelcel',0.54,1),
('GC De Bunder','Alle zalen',3,'Non-alcoholisch','Fanta 20 cl','flesje',24,'Koelcel',1.0,1),
('GC De Bunder','Alle zalen',12,'Bier','Kriek','flesje',24,'Koelcel',1.6,1),
('GC De Bunder','Alle zalen',13,'Bier','Rodenbach','flesje',24,'Koelcel',1.31,1),
('GC De Bunder','Alle zalen',16,'Bier','Carlsberg 0,0%','flesje',24,'Koelcel',1.44,1),
('GC De Bunder','Alle zalen',18,'Bier','Sportzot','flesje',24,'Koelcel',2.4,1),
('GC De Bunder','Alle zalen',10,'Bier','Duvel','flesje',24,'Koelcel',2.07,1),
('GC De Bunder','Alle zalen',14,'Bier','Sint Bernardus Prior','flesje',24,'Koelcel',1.84,1),
('GC De Bunder','Alle zalen',17,'Bier','Rochefort bruin 8°','flesje',24,'Koelcel',1.94,1),
('GC De Bunder','Alle zalen',19,'Bier','Sint Bernardus Tripel','flesje',24,'Koelcel',1.86,1),
('GC De Bunder','Alle zalen',15,'Bier','Klets blond','flesje',24,'Koelcel',2.37,1),
('GC De Bunder','Alle zalen',11,'Bier','Omer','flesje',24,'Koelcel',2.2,1),
('GC De Bunder','Alle zalen',7,'Non-alcoholisch','Tönissteiner citroen 25 cl','flesje',20,'Koelcel',1.24,1),
('GC De Bunder','Alle zalen',4,'Non-alcoholisch','Coca Cola 20 cl','flesje',24,'Koelcel',0.99,1),
('GC De Bunder','Alle zalen',5,'Non-alcoholisch','Coca Cola Zero 20 cl','flesje',24,'Koelcel',0.97,1),
('GC De Bunder','Alle zalen',6,'Non-alcoholisch','Ice Tea 25 cl','flesje',24,'Koelcel',0.99,1),
('GC De Bunder','Alle zalen',8,'Non-alcoholisch','Minute Maid 20 cl','flesje',24,'Koelcel',1.09,1),
('GC De Bunder','Alle zalen',9,'Bier','Jupiler','flesje',24,'Koelcel',1.0,1),
('GC De Bunder','Alle zalen',20,'Wijn & Cava','Cava zero','fles',6,'Koelcel',11.24,1),
('GC De Bunder','Alle zalen',21,'Wijn & Cava','Cava','fles',6,'Koelcel',10.86,1),
('GC De Bunder','Alle zalen',22,'Wijn & Cava','Witte wijn','fles',6,'Koelcel',9.22,1),
('GC De Bunder','Alle zalen',24,'Versnaperingen','Chips paprika','zakje',20,'Drankberging',0.9,1),
('GC De Bunder','Alle zalen',25,'Versnaperingen','Chips zout','zakje',20,'Drankberging',0.9,1),
('GC De Bunder','Alle zalen',23,'Wijn & Cava','Rode wijn','fles',6,'Drankberging',9.22,1),
('GC De Bunder','Alle zalen',26,'Divers','Koffiepad (MIKO)','stuk',1,'Drankberging',3.2,1),
('GC De Bunder','Alle zalen',27,'Divers','Restafvalzak','stuk',1,'Drankberging',2.8,1),
('GC De Bunder','Alle zalen',28,'Divers','PMD-zak','stuk',1,'Drankberging',0.15,1),
('GC De Bunder','Alle zalen',29,'Divers','GFT-zak','stuk',1,'Drankberging',0.12,1),
('GC De Bunder','Alle zalen',35,'Grote flessen','Tönissteiner citroen 75 cl','fles',6,'Drankberging',4.24,0),
('GC De Bunder','Alle zalen',31,'Grote flessen','Chaudfontaine plat 1 l','fles',6,'Drankberging',1.32,0),
('GC De Bunder','Alle zalen',32,'Grote flessen','Chaudfontaine bruis 1 l','fles',6,'Drankberging',1.32,0),
('GC De Bunder','Alle zalen',33,'Grote flessen','Coca Cola 1 l','fles',6,'Drankberging',3.87,0),
('GC De Bunder','Alle zalen',34,'Grote flessen','Coca Cola Zero 1 l','fles',6,'Drankberging',3.87,0),
('GC De Bunder','Alle zalen',30,'Grote flessen','Fruitsap 1 l','fles',6,'Drankberging',3.99,1),
('OC d''Oude Schole','Alle zalen',1,'Non-alcoholisch','Chaudfontaine plat 20 cl','flesje',24,'Koelcel',0.54,1),
('OC d''Oude Schole','Alle zalen',2,'Non-alcoholisch','Chaudfontaine bruis 20 cl','flesje',24,'Koelcel',0.54,1),
('OC d''Oude Schole','Alle zalen',3,'Non-alcoholisch','Fanta 20 cl','flesje',24,'Koelcel',1.0,1),
('OC d''Oude Schole','Alle zalen',12,'Bier','Kriek','flesje',24,'Koelcel',1.5,1),
('OC d''Oude Schole','Alle zalen',13,'Bier','Rodenbach','flesje',24,'Koelcel',1.31,1),
('OC d''Oude Schole','Alle zalen',16,'Bier','Carlsberg 0,0%','flesje',24,'Koelcel',1.44,1),
('OC d''Oude Schole','Alle zalen',18,'Bier','Sportzot','flesje',24,'Koelcel',2.4,1),
('OC d''Oude Schole','Alle zalen',10,'Bier','Duvel','flesje',24,'Koelcel',2.07,1),
('OC d''Oude Schole','Alle zalen',14,'Bier','Sint Bernardus Prior','flesje',24,'Koelcel',1.84,1),
('OC d''Oude Schole','Alle zalen',17,'Bier','Rochefort bruin 8°','flesje',24,'Koelcel',1.94,1),
('OC d''Oude Schole','Alle zalen',19,'Bier','Sint Bernardus Tripel','flesje',24,'Koelcel',1.86,1),
('OC d''Oude Schole','Alle zalen',15,'Bier','Klets blond','flesje',24,'Koelcel',2.37,1),
('OC d''Oude Schole','Alle zalen',11,'Bier','Omer','flesje',24,'Koelcel',2.2,1),
('OC d''Oude Schole','Alle zalen',7,'Non-alcoholisch','Tönissteiner citroen 25 cl','flesje',20,'Koelcel',1.24,1),
('OC d''Oude Schole','Alle zalen',4,'Non-alcoholisch','Coca Cola 20 cl','flesje',24,'Koelcel',0.99,1),
('OC d''Oude Schole','Alle zalen',5,'Non-alcoholisch','Coca Cola Zero 20 cl','flesje',24,'Koelcel',0.97,1),
('OC d''Oude Schole','Alle zalen',6,'Non-alcoholisch','Ice Tea 25 cl','flesje',24,'Koelcel',0.99,1),
('OC d''Oude Schole','Alle zalen',8,'Non-alcoholisch','Minute Maid 20 cl','flesje',24,'Koelcel',1.09,1),
('OC d''Oude Schole','Alle zalen',9,'Bier','Jupiler','flesje',24,'Koelcel',1.0,1),
('OC d''Oude Schole','Alle zalen',20,'Wijn & Cava','Cava zero','fles',6,'Koelcel',11.24,1),
('OC d''Oude Schole','Alle zalen',21,'Wijn & Cava','Cava','fles',6,'Koelcel',10.86,1),
('OC d''Oude Schole','Alle zalen',22,'Wijn & Cava','Witte wijn','fles',6,'Koelcel',9.22,1),
('OC d''Oude Schole','Alle zalen',24,'Versnaperingen','Chips paprika','zakje',20,'Drankberging',0.9,1),
('OC d''Oude Schole','Alle zalen',25,'Versnaperingen','Chips zout','zakje',20,'Drankberging',0.9,1),
('OC d''Oude Schole','Alle zalen',23,'Wijn & Cava','Rode wijn','fles',6,'Drankberging',9.22,1),
('OC d''Oude Schole','Alle zalen',26,'Divers','Koffiepad (MIKO)','stuk',1,'Drankberging',3.2,1),
('OC d''Oude Schole','Alle zalen',27,'Divers','Restafvalzak','stuk',1,'Drankberging',2.8,1),
('OC d''Oude Schole','Alle zalen',28,'Divers','PMD-zak','stuk',1,'Drankberging',0.15,1),
('OC d''Oude Schole','Alle zalen',29,'Divers','GFT-zak','stuk',1,'Drankberging',0.12,1),
('OC d''Oude Schole','Alle zalen',35,'Grote flessen','Tönissteiner citroen 75 cl','fles',6,'Drankberging',4.24,0),
('OC d''Oude Schole','Alle zalen',31,'Grote flessen','Chaudfontaine plat 1 l','fles',6,'Drankberging',1.32,0),
('OC d''Oude Schole','Alle zalen',32,'Grote flessen','Chaudfontaine bruis 1 l','fles',6,'Drankberging',1.32,0),
('OC d''Oude Schole','Alle zalen',33,'Grote flessen','Coca Cola 1 l','fles',6,'Drankberging',3.87,0),
('OC d''Oude Schole','Alle zalen',34,'Grote flessen','Coca Cola Zero 1 l','fles',6,'Drankberging',3.87,0),
('OC d''Oude Schole','Alle zalen',30,'Grote flessen','Fruitsap 1 l','fles',6,'Drankberging',3.99,1),
('JC De 4link','Alle zalen',1,'Non-alcoholisch','Chaudfontaine plat 20 cl','flesje',24,'Koelcel',0.54,1),
('JC De 4link','Alle zalen',2,'Non-alcoholisch','Chaudfontaine bruis 20 cl','flesje',24,'Koelcel',0.54,1),
('JC De 4link','Alle zalen',3,'Non-alcoholisch','Fanta 20 cl','flesje',24,'Koelcel',1.0,1),
('JC De 4link','Alle zalen',12,'Bier','Kriek','flesje',24,'Koelcel',1.5,1),
('JC De 4link','Alle zalen',13,'Bier','Rodenbach','flesje',24,'Koelcel',1.31,1),
('JC De 4link','Alle zalen',16,'Bier','Carlsberg 0,0%','flesje',24,'Koelcel',1.44,1),
('JC De 4link','Alle zalen',18,'Bier','Sportzot','flesje',24,'Koelcel',2.4,1),
('JC De 4link','Alle zalen',10,'Bier','Duvel','flesje',24,'Koelcel',2.07,1),
('JC De 4link','Alle zalen',14,'Bier','Sint Bernardus Prior','flesje',24,'Koelcel',1.84,1),
('JC De 4link','Alle zalen',17,'Bier','Rochefort bruin 8°','flesje',24,'Koelcel',1.94,1),
('JC De 4link','Alle zalen',19,'Bier','Sint Bernardus Tripel','flesje',24,'Koelcel',1.86,1),
('JC De 4link','Alle zalen',15,'Bier','Klets blond','flesje',24,'Koelcel',2.37,1),
('JC De 4link','Alle zalen',11,'Bier','Omer','flesje',24,'Koelcel',2.2,1),
('JC De 4link','Alle zalen',7,'Non-alcoholisch','Tönissteiner citroen 25 cl','flesje',20,'Koelcel',1.24,1),
('JC De 4link','Alle zalen',4,'Non-alcoholisch','Coca Cola 20 cl','flesje',24,'Koelcel',0.99,1),
('JC De 4link','Alle zalen',5,'Non-alcoholisch','Coca Cola Zero 20 cl','flesje',24,'Koelcel',0.97,1),
('JC De 4link','Alle zalen',6,'Non-alcoholisch','Ice Tea 25 cl','flesje',24,'Koelcel',0.99,1),
('JC De 4link','Alle zalen',8,'Non-alcoholisch','Minute Maid 20 cl','flesje',24,'Koelcel',1.09,1),
('JC De 4link','Alle zalen',9,'Bier','Jupiler','flesje',24,'Koelcel',1.0,1),
('JC De 4link','Alle zalen',20,'Wijn & Cava','Cava zero','fles',6,'Koelcel',11.24,1),
('JC De 4link','Alle zalen',21,'Wijn & Cava','Cava','fles',6,'Koelcel',10.86,1),
('JC De 4link','Alle zalen',22,'Wijn & Cava','Witte wijn','fles',6,'Koelcel',9.22,1),
('JC De 4link','Alle zalen',24,'Versnaperingen','Chips paprika','zakje',20,'Drankberging',0.9,1),
('JC De 4link','Alle zalen',25,'Versnaperingen','Chips zout','zakje',20,'Drankberging',0.9,1),
('JC De 4link','Alle zalen',23,'Wijn & Cava','Rode wijn','fles',6,'Drankberging',9.22,1),
('JC De 4link','Alle zalen',26,'Divers','Koffiepad (MIKO)','stuk',1,'Drankberging',3.2,1),
('JC De 4link','Alle zalen',27,'Divers','Restafvalzak','stuk',1,'Drankberging',2.8,1),
('JC De 4link','Alle zalen',28,'Divers','PMD-zak','stuk',1,'Drankberging',0.15,1),
('JC De 4link','Alle zalen',29,'Divers','GFT-zak','stuk',1,'Drankberging',0.12,1),
('JC De 4link','Alle zalen',35,'Grote flessen','Tönissteiner citroen 75 cl','fles',6,'Drankberging',4.24,0),
('JC De 4link','Alle zalen',31,'Grote flessen','Chaudfontaine plat 1 l','fles',6,'Drankberging',1.32,0),
('JC De 4link','Alle zalen',32,'Grote flessen','Chaudfontaine bruis 1 l','fles',6,'Drankberging',1.32,0),
('JC De 4link','Alle zalen',33,'Grote flessen','Coca Cola 1 l','fles',6,'Drankberging',3.87,0),
('JC De 4link','Alle zalen',34,'Grote flessen','Coca Cola Zero 1 l','fles',6,'Drankberging',3.87,0),
('JC De 4link','Alle zalen',30,'Grote flessen','Fruitsap 1 l','fles',6,'Drankberging',3.99,1),
('OC Den Ommeganck','Alle zalen',1,'Non-alcoholisch','Chaudfontaine plat 20 cl','flesje',24,'Koelcel',0.54,1),
('OC Den Ommeganck','Alle zalen',2,'Non-alcoholisch','Chaudfontaine bruis 20 cl','flesje',24,'Koelcel',0.54,1),
('OC Den Ommeganck','Alle zalen',3,'Non-alcoholisch','Fanta 20 cl','flesje',24,'Koelcel',1.0,1),
('OC Den Ommeganck','Alle zalen',12,'Bier','Kriek','flesje',24,'Koelcel',1.5,1),
('OC Den Ommeganck','Alle zalen',13,'Bier','Rodenbach','flesje',24,'Koelcel',1.31,1),
('OC Den Ommeganck','Alle zalen',16,'Bier','Carlsberg 0,0%','flesje',24,'Koelcel',1.44,1),
('OC Den Ommeganck','Alle zalen',18,'Bier','Sportzot','flesje',24,'Koelcel',2.4,1),
('OC Den Ommeganck','Alle zalen',10,'Bier','Duvel','flesje',24,'Koelcel',2.07,1),
('OC Den Ommeganck','Alle zalen',14,'Bier','Sint Bernardus Prior','flesje',24,'Koelcel',1.84,1),
('OC Den Ommeganck','Alle zalen',17,'Bier','Rochefort bruin 8°','flesje',24,'Koelcel',1.94,1),
('OC Den Ommeganck','Alle zalen',19,'Bier','Sint Bernardus Tripel','flesje',24,'Koelcel',1.86,1),
('OC Den Ommeganck','Alle zalen',15,'Bier','Klets blond','flesje',24,'Koelcel',2.37,1),
('OC Den Ommeganck','Alle zalen',11,'Bier','Omer','flesje',24,'Koelcel',2.2,1),
('OC Den Ommeganck','Alle zalen',7,'Non-alcoholisch','Tönissteiner citroen 25 cl','flesje',20,'Koelcel',1.24,1),
('OC Den Ommeganck','Alle zalen',4,'Non-alcoholisch','Coca Cola 20 cl','flesje',24,'Koelcel',0.99,1),
('OC Den Ommeganck','Alle zalen',5,'Non-alcoholisch','Coca Cola Zero 20 cl','flesje',24,'Koelcel',0.97,1),
('OC Den Ommeganck','Alle zalen',6,'Non-alcoholisch','Ice Tea 25 cl','flesje',24,'Koelcel',0.99,1),
('OC Den Ommeganck','Alle zalen',8,'Non-alcoholisch','Minute Maid 20 cl','flesje',24,'Koelcel',1.09,1),
('OC Den Ommeganck','Alle zalen',9,'Bier','Jupiler','flesje',24,'Koelcel',1.0,1),
('OC Den Ommeganck','Alle zalen',20,'Wijn & Cava','Cava zero','fles',6,'Koelcel',11.24,1),
('OC Den Ommeganck','Alle zalen',21,'Wijn & Cava','Cava','fles',6,'Koelcel',10.86,1),
('OC Den Ommeganck','Alle zalen',22,'Wijn & Cava','Witte wijn','fles',6,'Koelcel',9.22,1),
('OC Den Ommeganck','Alle zalen',24,'Versnaperingen','Chips paprika','zakje',20,'Drankberging',0.9,1),
('OC Den Ommeganck','Alle zalen',25,'Versnaperingen','Chips zout','zakje',20,'Drankberging',0.9,1),
('OC Den Ommeganck','Alle zalen',23,'Wijn & Cava','Rode wijn','fles',6,'Drankberging',9.22,1),
('OC Den Ommeganck','Alle zalen',26,'Divers','Koffiepad (MIKO)','stuk',1,'Drankberging',3.2,1),
('OC Den Ommeganck','Alle zalen',27,'Divers','Restafvalzak','stuk',1,'Drankberging',2.8,1),
('OC Den Ommeganck','Alle zalen',28,'Divers','PMD-zak','stuk',1,'Drankberging',0.15,1),
('OC Den Ommeganck','Alle zalen',29,'Divers','GFT-zak','stuk',1,'Drankberging',0.12,1),
('OC Den Ommeganck','Alle zalen',35,'Grote flessen','Tönissteiner citroen 75 cl','fles',6,'Drankberging',4.24,0),
('OC Den Ommeganck','Alle zalen',31,'Grote flessen','Chaudfontaine plat 1 l','fles',6,'Drankberging',1.32,0),
('OC Den Ommeganck','Alle zalen',32,'Grote flessen','Chaudfontaine bruis 1 l','fles',6,'Drankberging',1.32,0),
('OC Den Ommeganck','Alle zalen',33,'Grote flessen','Coca Cola 1 l','fles',6,'Drankberging',3.87,0),
('OC Den Ommeganck','Alle zalen',34,'Grote flessen','Coca Cola Zero 1 l','fles',6,'Drankberging',3.87,0),
('OC Den Ommeganck','Alle zalen',30,'Grote flessen','Fruitsap 1 l','fles',6,'Drankberging',3.99,1),
('OC ''t Torreke','Alle zalen',1,'Non-alcoholisch','Chaudfontaine plat 20 cl','flesje',24,'Koelcel',0.54,1),
('OC ''t Torreke','Alle zalen',2,'Non-alcoholisch','Chaudfontaine bruis 20 cl','flesje',24,'Koelcel',0.54,1),
('OC ''t Torreke','Alle zalen',3,'Non-alcoholisch','Fanta 20 cl','flesje',24,'Koelcel',1.0,1),
('OC ''t Torreke','Alle zalen',12,'Bier','Kriek','flesje',24,'Koelcel',1.5,1),
('OC ''t Torreke','Alle zalen',13,'Bier','Rodenbach','flesje',24,'Koelcel',1.31,1),
('OC ''t Torreke','Alle zalen',16,'Bier','Carlsberg 0,0%','flesje',24,'Koelcel',1.44,1),
('OC ''t Torreke','Alle zalen',18,'Bier','Sportzot','flesje',24,'Koelcel',2.4,1),
('OC ''t Torreke','Alle zalen',10,'Bier','Duvel','flesje',24,'Koelcel',2.07,1),
('OC ''t Torreke','Alle zalen',14,'Bier','Sint Bernardus Prior','flesje',24,'Koelcel',1.84,1),
('OC ''t Torreke','Alle zalen',17,'Bier','Rochefort bruin 8°','flesje',24,'Koelcel',1.94,1),
('OC ''t Torreke','Alle zalen',19,'Bier','Sint Bernardus Tripel','flesje',24,'Koelcel',1.86,1),
('OC ''t Torreke','Alle zalen',15,'Bier','Klets blond','flesje',24,'Koelcel',2.37,1),
('OC ''t Torreke','Alle zalen',11,'Bier','Omer','flesje',24,'Koelcel',2.2,1),
('OC ''t Torreke','Alle zalen',7,'Non-alcoholisch','Tönissteiner citroen 25 cl','flesje',20,'Koelcel',1.24,1),
('OC ''t Torreke','Alle zalen',4,'Non-alcoholisch','Coca Cola 20 cl','flesje',24,'Koelcel',0.99,1),
('OC ''t Torreke','Alle zalen',5,'Non-alcoholisch','Coca Cola Zero 20 cl','flesje',24,'Koelcel',0.97,1),
('OC ''t Torreke','Alle zalen',6,'Non-alcoholisch','Ice Tea 25 cl','flesje',24,'Koelcel',0.99,1),
('OC ''t Torreke','Alle zalen',8,'Non-alcoholisch','Minute Maid 20 cl','flesje',24,'Koelcel',1.09,1),
('OC ''t Torreke','Alle zalen',9,'Bier','Jupiler','flesje',24,'Koelcel',1.0,1),
('OC ''t Torreke','Alle zalen',20,'Wijn & Cava','Cava zero','fles',6,'Koelcel',11.24,1),
('OC ''t Torreke','Alle zalen',21,'Wijn & Cava','Cava','fles',6,'Koelcel',10.86,1),
('OC ''t Torreke','Alle zalen',22,'Wijn & Cava','Witte wijn','fles',6,'Koelcel',9.22,1),
('OC ''t Torreke','Alle zalen',24,'Versnaperingen','Chips paprika','zakje',20,'Drankberging',0.9,1),
('OC ''t Torreke','Alle zalen',25,'Versnaperingen','Chips zout','zakje',20,'Drankberging',0.9,1),
('OC ''t Torreke','Alle zalen',23,'Wijn & Cava','Rode wijn','fles',6,'Drankberging',9.22,1),
('OC ''t Torreke','Alle zalen',26,'Divers','Koffiepad (MIKO)','stuk',1,'Drankberging',3.2,1),
('OC ''t Torreke','Alle zalen',27,'Divers','Restafvalzak','stuk',1,'Drankberging',2.8,1),
('OC ''t Torreke','Alle zalen',28,'Divers','PMD-zak','stuk',1,'Drankberging',0.15,1),
('OC ''t Torreke','Alle zalen',29,'Divers','GFT-zak','stuk',1,'Drankberging',0.12,1),
('OC ''t Torreke','Alle zalen',35,'Grote flessen','Tönissteiner citroen 75 cl','fles',6,'Drankberging',4.24,0),
('OC ''t Torreke','Alle zalen',31,'Grote flessen','Chaudfontaine plat 1 l','fles',6,'Drankberging',1.32,0),
('OC ''t Torreke','Alle zalen',32,'Grote flessen','Chaudfontaine bruis 1 l','fles',6,'Drankberging',1.32,0),
('OC ''t Torreke','Alle zalen',33,'Grote flessen','Coca Cola 1 l','fles',6,'Drankberging',3.87,0),
('OC ''t Torreke','Alle zalen',34,'Grote flessen','Coca Cola Zero 1 l','fles',6,'Drankberging',3.87,0),
('OC ''t Torreke','Alle zalen',30,'Grote flessen','Fruitsap 1 l','fles',6,'Drankberging',3.99,1),
('OC Oud Gemeentehuis','Alle zalen',1,'Non-alcoholisch','Chaudfontaine plat 20 cl','flesje',24,'Koelcel',0.54,1),
('OC Oud Gemeentehuis','Alle zalen',2,'Non-alcoholisch','Chaudfontaine bruis 20 cl','flesje',24,'Koelcel',0.54,1),
('OC Oud Gemeentehuis','Alle zalen',3,'Non-alcoholisch','Fanta 20 cl','flesje',24,'Koelcel',1.0,1),
('OC Oud Gemeentehuis','Alle zalen',12,'Bier','Kriek','flesje',24,'Koelcel',1.5,1),
('OC Oud Gemeentehuis','Alle zalen',13,'Bier','Rodenbach','flesje',24,'Koelcel',1.31,1),
('OC Oud Gemeentehuis','Alle zalen',16,'Bier','Carlsberg 0,0%','flesje',24,'Koelcel',1.44,1),
('OC Oud Gemeentehuis','Alle zalen',18,'Bier','Sportzot','flesje',24,'Koelcel',2.4,1),
('OC Oud Gemeentehuis','Alle zalen',10,'Bier','Duvel','flesje',24,'Koelcel',2.07,1),
('OC Oud Gemeentehuis','Alle zalen',14,'Bier','Sint Bernardus Prior','flesje',24,'Koelcel',1.84,1),
('OC Oud Gemeentehuis','Alle zalen',17,'Bier','Rochefort bruin 8°','flesje',24,'Koelcel',1.94,1),
('OC Oud Gemeentehuis','Alle zalen',19,'Bier','Sint Bernardus Tripel','flesje',24,'Koelcel',1.86,1),
('OC Oud Gemeentehuis','Alle zalen',15,'Bier','Klets blond','flesje',24,'Koelcel',2.37,1),
('OC Oud Gemeentehuis','Alle zalen',11,'Bier','Omer','flesje',24,'Koelcel',2.2,1),
('OC Oud Gemeentehuis','Alle zalen',7,'Non-alcoholisch','Tönissteiner citroen 25 cl','flesje',20,'Koelcel',1.24,1),
('OC Oud Gemeentehuis','Alle zalen',4,'Non-alcoholisch','Coca Cola 20 cl','flesje',24,'Koelcel',0.99,1),
('OC Oud Gemeentehuis','Alle zalen',5,'Non-alcoholisch','Coca Cola Zero 20 cl','flesje',24,'Koelcel',0.97,1),
('OC Oud Gemeentehuis','Alle zalen',6,'Non-alcoholisch','Ice Tea 25 cl','flesje',24,'Koelcel',0.99,1),
('OC Oud Gemeentehuis','Alle zalen',8,'Non-alcoholisch','Minute Maid 20 cl','flesje',24,'Koelcel',1.09,1),
('OC Oud Gemeentehuis','Alle zalen',9,'Bier','Jupiler','flesje',24,'Koelcel',1.0,1),
('OC Oud Gemeentehuis','Alle zalen',20,'Wijn & Cava','Cava zero','fles',6,'Koelcel',11.24,1),
('OC Oud Gemeentehuis','Alle zalen',21,'Wijn & Cava','Cava','fles',6,'Koelcel',10.86,1),
('OC Oud Gemeentehuis','Alle zalen',22,'Wijn & Cava','Witte wijn','fles',6,'Koelcel',9.22,1),
('OC Oud Gemeentehuis','Alle zalen',24,'Versnaperingen','Chips paprika','zakje',20,'Drankberging',0.9,1),
('OC Oud Gemeentehuis','Alle zalen',25,'Versnaperingen','Chips zout','zakje',20,'Drankberging',0.9,1),
('OC Oud Gemeentehuis','Alle zalen',23,'Wijn & Cava','Rode wijn','fles',6,'Drankberging',9.22,1),
('OC Oud Gemeentehuis','Alle zalen',26,'Divers','Koffiepad (MIKO)','stuk',1,'Drankberging',3.2,1),
('OC Oud Gemeentehuis','Alle zalen',27,'Divers','Restafvalzak','stuk',1,'Drankberging',2.8,1),
('OC Oud Gemeentehuis','Alle zalen',28,'Divers','PMD-zak','stuk',1,'Drankberging',0.15,1),
('OC Oud Gemeentehuis','Alle zalen',29,'Divers','GFT-zak','stuk',1,'Drankberging',0.12,1),
('OC Oud Gemeentehuis','Alle zalen',35,'Grote flessen','Tönissteiner citroen 75 cl','fles',6,'Drankberging',4.24,0),
('OC Oud Gemeentehuis','Alle zalen',31,'Grote flessen','Chaudfontaine plat 1 l','fles',6,'Drankberging',1.32,0),
('OC Oud Gemeentehuis','Alle zalen',32,'Grote flessen','Chaudfontaine bruis 1 l','fles',6,'Drankberging',1.32,0),
('OC Oud Gemeentehuis','Alle zalen',33,'Grote flessen','Coca Cola 1 l','fles',6,'Drankberging',3.87,0),
('OC Oud Gemeentehuis','Alle zalen',34,'Grote flessen','Coca Cola Zero 1 l','fles',6,'Drankberging',3.87,0),
('OC Oud Gemeentehuis','Alle zalen',30,'Grote flessen','Fruitsap 1 l','fles',6,'Drankberging',3.99,1);
